#[repr(i32)]
pub enum Key {
    A = raylib_sys::KeyboardKey_KEY_A as i32,
    B = raylib_sys::KeyboardKey_KEY_B as i32,
    C = raylib_sys::KeyboardKey_KEY_C as i32,
    D = raylib_sys::KeyboardKey_KEY_D as i32,
    E = raylib_sys::KeyboardKey_KEY_E as i32,
    F = raylib_sys::KeyboardKey_KEY_F as i32,
    G = raylib_sys::KeyboardKey_KEY_G as i32,
    H = raylib_sys::KeyboardKey_KEY_H as i32,
    I = raylib_sys::KeyboardKey_KEY_I as i32,
    J = raylib_sys::KeyboardKey_KEY_J as i32,
    K = raylib_sys::KeyboardKey_KEY_K as i32,
    L = raylib_sys::KeyboardKey_KEY_L as i32,
    M = raylib_sys::KeyboardKey_KEY_M as i32,
    N = raylib_sys::KeyboardKey_KEY_N as i32,
    O = raylib_sys::KeyboardKey_KEY_O as i32,
    P = raylib_sys::KeyboardKey_KEY_P as i32,
    Q = raylib_sys::KeyboardKey_KEY_Q as i32,
    R = raylib_sys::KeyboardKey_KEY_R as i32,
    S = raylib_sys::KeyboardKey_KEY_S as i32,
    T = raylib_sys::KeyboardKey_KEY_T as i32,
    U = raylib_sys::KeyboardKey_KEY_U as i32,
    V = raylib_sys::KeyboardKey_KEY_V as i32,
    W = raylib_sys::KeyboardKey_KEY_W as i32,
    X = raylib_sys::KeyboardKey_KEY_X as i32,
    Y = raylib_sys::KeyboardKey_KEY_Y as i32,
    Z = raylib_sys::KeyboardKey_KEY_Z as i32,
    Enter = raylib_sys::KeyboardKey_KEY_ENTER as i32,
}
