permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:
name: test
jobs:
  required:
    runs-on: ubuntu-latest
    name: ubuntu / ${{ matrix.toolchain }}
    strategy:
      matrix:
        toolchain: [nightly]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install raylib
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev
          git clone https://github.com/raysan5/raylib.git raylib
          cd raylib/src/
          make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=SHARED
          sudo make install RAYLIB_LIBTYPE=SHARED
          sudo cp --update rcamera.h /usr/local/include/rcamera.h
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      # https://twitter.com/jonhoo/status/1571290371124260865
      - name: cargo test --locked
        run: cargo test --locked --all-features --lib --bins --tests --examples -- --test-threads=1
      - name: cargo bench
        run: cargo bench
